Repository Side-Effect-Team/side-effect-frontend, pull requests merged in 2023-06, with the labels that each got.

#104 FE: 마이페이지 이미지 변경 및 닉네임 중복검사
  apis/ApplicantAPI.ts
  apis/LikeAndCommentAPI.ts
  apis/NotificationAPI.ts
  apis/RecruitBoardAPI.ts
  apis/UserAPI.ts
  components/BoardCard/index.tsx
  components/hocs/withAuth.tsx
  components/pages/mypage/Profile/Introduction/index.tsx
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  hooks/common/useInputImage.ts
  hooks/queries/useGetMypageData.ts
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
  pages/recruits/index.tsx
  public/images/mypageDefaultImage.png
Labels: feat, update

#106 Feat/dark mode
  components/Alarm/styled.ts
  components/BoardCard/styled.ts
  components/Carousel/BatchCarousel/styled.ts
  components/DarkModeToggle/index.tsx
  components/DarkModeToggle/styled.ts
  components/Footer/styled.ts
  components/Header/styled.ts
  components/Layout/index.tsx
  components/Modals/LoginModal/Login.tsx
  components/Modals/LoginModal/LoginModal.tsx
  components/Modals/LoginModal/LoginTitle.tsx
  components/Modals/LoginModal/OAuthLoginButton/styled.ts
  components/Modals/LoginModal/styled.ts
  components/Modals/ManageTeamModal/FilterTab/index.tsx
  components/Modals/ManageTeamModal/FilterTab/styled.ts
  components/Modals/ManageTeamModal/ManageCard/index.tsx
  components/Modals/ManageTeamModal/ManageCard/styled.ts
  components/Modals/ManageTeamModal/ManageList/index.tsx
  components/Modals/ManageTeamModal/ManageList/styled.ts
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Modals/ManageTeamModal/PositionFilterTab/index.tsx
  components/Modals/ManageTeamModal/PositionFilterTab/styled.ts
  components/Modals/ManageTeamModal/styled.ts
  components/Nodata/index.tsx
  components/ScrollToTop/styled.ts
  components/Search/styled.ts
  components/SelectBox/styled.ts
  components/Skeleton/BoardCardSkeleton/styled.ts
  components/Toast/styled.ts
  components/pages/post/common/PageLayout.styled.ts
  components/pages/post/common/PostForm.styled.ts
  pages/_document.tsx
  pages/index.tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
  public/images/Nodata.png
  public/images/Nodata.svg
  store/darkModeSlice.ts
  store/store.ts
  styled.d.ts
  styles/Global.ts
  styles/Theme.ts
Labels: feat, design

#108 FE: 모집 카드 구현에 따른 카드 컴포넌트 분리, 계정 탈퇴 및 마이페이지 탭 이슈 수정
  apis/UserAPI.ts
  components/Alarm/AlarmList.tsx
  components/Alarm/styled.ts
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  components/Button/HeartButton/index.tsx
  components/Button/HeartButton/styled.ts
  components/Button/styled.ts
  components/Card/ApplyBoardCard/index.tsx
  components/Card/ApplyBoardCard/styled.ts
  components/Card/ProjectCard/index.tsx
  components/Card/ProjectCard/styled.ts
  components/Card/RecruitCard/index.tsx
  components/Card/RecruitCard/styled.ts
  components/Carousel/BatchCarousel/index.tsx
  components/Carousel/BatchCarousel/styled.ts
  components/Input/index.tsx
  components/Input/styled.ts
  components/Search/filter.tsx
  components/Search/styled.ts
  components/Skeleton/AlarmSkeleton/styled.ts
  components/Skeleton/ProjectCardSkeleton/index.tsx
  components/Skeleton/ProjectCardSkeleton/styled.ts
  components/Skeleton/RecruitCardSkeleton/index.tsx
  components/Skeleton/RecruitCardSkeleton/styled.ts
  components/Tag/index.tsx
  components/Tag/styled.ts
  components/pages/mypage/Account/index.tsx
  components/pages/mypage/Account/style.ts
  components/pages/mypage/Profile/Info/styled.ts
  components/pages/mypage/Profile/Introduction/styled.ts
  components/pages/mypage/Profile/Skill/styled.ts
  components/pages/mypage/TabApplyBoards/index.tsx
  components/pages/mypage/TabApplyBoards/styled.ts
  components/pages/mypage/TabBoards/index.tsx
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  components/pages/mypageEdit/Info/styled.ts
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/mypageEdit/Skill/styled.ts
  components/pages/project/ProjectLIst/index.tsx
  hooks/mutations/useDeleteAccount.ts
  hooks/queries/useGetProjectData.tsx
  pages/index.tsx
  pages/mypage/[mypageId].tsx
  pages/mypage/index.tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
  public/images/ProjectBackground.png
  styled.d.ts
  styles/Theme.ts
Labels: feat, fix, design, refactor

#110 FE: 포지션 지원 기능 추가 및 기타 리팩토링
  apis/ApplicantAPI.ts
  apis/ProjectAPI.ts
  apis/RecruitBoardAPI.ts
  apis/UserAPI.ts
  components/Card/RecruitCard/index.tsx
  components/Carousel/BatchCarousel/index.tsx
  components/Header/GlobalNavBar/index.tsx
  components/Header/GlobalNavBar/styled.ts
  components/Header/LoggedInMenuBox/index.tsx
  components/Header/LoggedInMenuBox/styled.ts
  components/Header/MobileMenuBox/index.tsx
  components/Header/MobileMenuBox/styled.ts
  components/Header/index.tsx
  components/Layout/index.tsx
  components/pages/detailPage/CommentBox/index.tsx
  components/pages/detailPage/CommentItem/index.tsx
  components/pages/detailPage/PositionDetail/index.tsx
  components/pages/detailPage/PositionDetail/styled.ts
  components/pages/detailPage/PositionRow/index.tsx
  components/pages/detailPage/PositionRow/styled.ts
  components/pages/detailPage/PostData/index.tsx
  pages/post/recruit.tsx
  pages/projects/[projectId].tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/index.tsx
  public/images/default-input-image.png
  types/recruit.ts
Labels: feat, fix, refactor

#111 Feat/ranking card
  apis/ProjectAPI.ts
  components/Card/RankingCard/index.tsx
  components/Card/RankingCard/styled.ts
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Skeleton/ProjectCardSkeleton/index.tsx
  pages/projects/index.tsx
  public/images/black.jpeg
Labels: feat, design

#114 FE: 모집카드의 숨겨진 태그 갯수 표시 및 마이페이지 빈값 전달 안되는 이슈 해결
  apis/UserAPI.ts
  components/Alarm/styled.ts
  components/Boarder/SectionBorder/index.tsx
  components/Boarder/SectionBorder/styled.ts
  components/Button/HeartButton/styled.ts
  components/Button/styled.ts
  components/Card/ApplyBoardCard/index.tsx
  components/Card/ApplyCard/index.tsx
  components/Card/ApplyCard/styled.ts
  components/Card/ProjectCard/index.tsx
  components/Card/ProjectCard/styled.ts
  components/Card/RecruitCard/index.tsx
  components/Card/RecruitCard/styled.ts
  components/Footer/CardFooter/index.tsx
  components/Footer/CardFooter/styled.ts
  components/Input/index.tsx
  components/Input/styled.ts
  components/Search/filter.tsx
  components/Skeleton/AlarmSkeleton/styled.ts
  components/Tag/TagBox/index.tsx
  components/Tag/TagBox/styled.ts
  components/Tag/styled.ts
  components/hocs/withAuth.tsx
  components/pages/mypage/Profile/Info/index.tsx
  components/pages/mypage/Profile/Info/styled.ts
  components/pages/mypage/Profile/Introduction/index.tsx
  components/pages/mypage/Profile/Introduction/styled.ts
  components/pages/mypage/Profile/Skill/index.tsx
  components/pages/mypage/Profile/Skill/styled.ts
  components/pages/mypage/Profile/index.tsx
  components/pages/mypage/Profile/styled.ts
  components/pages/mypage/TabApplyBoards/index.tsx
  components/pages/mypage/TabBoards/index.tsx
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Info/styled.ts
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/mypageEdit/Skill/index.tsx
  components/pages/mypageEdit/Skill/styled.ts
  enum/index.ts
  hooks/mutations/useAddLikeProject.ts
  hooks/mutations/useAddLikeRecuit.ts
  hooks/mutations/useCancelApply.ts
  hooks/mutations/useDeleteAccount.ts
  hooks/mutations/useEditProfile.ts
  hooks/queries/useGetAlarmDataAll.ts
  hooks/queries/useGetMypageData.ts
  hooks/queries/useGetPofileData.ts
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
  styled.d.ts
  styles/Theme.ts
  types/projects.ts
  utils/compareData.ts
  utils/translateData.ts
  utils/updateData.ts
Labels: feat, fix, design, refactor

#115 Refactor/login modal
  apis/UserAPI.ts
  apis/customAxios.ts
  components/Modals/LoginModal/Login.tsx
  components/Modals/LoginModal/LoginModal.tsx
  components/Modals/LoginModal/LoginTitle.tsx
  components/Modals/LoginModal/RegisterView/RegisterNickname.tsx
  components/Modals/LoginModal/RegisterView/RegisterSuccess.tsx
  components/Modals/LoginModal/RegisterView/RegisterUserInfo.tsx
  components/Modals/LoginModal/RegisterView/styled.ts
  components/Modals/LoginModal/styled.ts
  components/Modals/ManageTeamModal/ManageCard/index.tsx
  components/Modals/ManageTeamModal/ManageCard/styled.ts
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Modals/ManageTeamModal/PositionFilterTab/index.tsx
  components/Modals/ManageTeamModal/PositionFilterTab/styled.ts
  enum/index.ts
  hooks/common/useLogin.ts
  pages/_app.tsx
  public/images/handShake.png
  store/loginViewTransitionSlice.ts
Labels: fix, design, refactor

#117 Feat/마이페이지탭
  components/Button/styled.ts
  components/Header/GlobalNavBar/styled.ts
  components/Header/LoggedInMenuBox/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/avatar.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/Introduction/introduction.tsx
  components/pages/mypageEdit/Introduction/nickname.tsx
  hooks/mutations/useDeleteAccount.ts
  pages/mypage/profileEdit/index.tsx
Labels: design, refactor

#123 fix: dark mode toggle
  components/DarkModeToggle/index.tsx
  components/DarkModeToggle/styled.ts
  styles/Global.ts
Labels: fix

#125 FE: bug fix
  components/Banner/index.tsx
  components/Header/GlobalNavBar/styled.ts
  components/pages/post/TagBox/index.tsx
  components/pages/post/TagBox/styled.ts
  components/pages/recruits/RecruitContents/index.tsx
  components/pages/recruits/RecruitContents/styled.ts
  components/pages/recruits/RecruitFilters/styled.ts
  pages/recruits/index.tsx
  styles/Global.ts
  styles/Theme.ts
Labels: fix

#127 FE: 카드컴포넌트 변경
  components/Boarder/SectionBorder/styled.ts
  components/Button/styled.ts
  components/Card/ProjectCard/index.tsx
  components/Card/ProjectCard/styled.ts
  components/Card/RecruitCard/index.tsx
  components/Card/RecruitCard/styled.ts
  components/Carousel/BatchCarousel/styled.ts
  components/Footer/CardFooter/index.tsx
  components/Footer/CardFooter/styled.ts
  components/Modals/ManageTeamModal/ManageCard/ButtonSection/index.tsx
  components/Tag/TagBox/index.tsx
  components/Tag/TagBox/styled.ts
  components/Tag/styled.ts
  components/pages/mypage/Profile/Info/styled.ts
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypageEdit/Info/styled.ts
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/mypageEdit/Skill/styled.ts
  components/pages/project/ProjectLIst/styled.ts
  styled.d.ts
  styles/Theme.ts
  utils/getDate.ts
Labels: feat, design

#131 FE: 푸터 추가
  components/Footer/index.tsx
  components/Footer/styled.ts
  components/Header/GlobalNavBar/index.tsx
  components/Header/GlobalNavBar/styled.ts
  public/images/mainLogo.svg
  styles/Theme.ts
Labels: feat

#134 Design: 랜딩페이지5
  components/Modals/ManageTeamModal/ManageCard/ButtonSection/index.tsx
  components/Modals/ManageTeamModal/ManageCard/styled.ts
  components/pages/landing/fifth/LeftSection/index.tsx
  components/pages/landing/fifth/LeftSection/styled.ts
  components/pages/landing/fifth/RightSection/ProjectInfo/index.tsx
  components/pages/landing/fifth/RightSection/ProjectInfo/styled.ts
  components/pages/landing/fifth/RightSection/index.tsx
  components/pages/landing/fifth/RightSection/styled.ts
  components/pages/landing/fifth/index.tsx
  components/pages/landing/fifth/styled.ts
  components/pages/landing/styled.ts
  package-lock.json
  package.json
  pages/index.tsx
Labels: feat, design

#136 update: 리프레쉬토큰이 없거나 만료 등 정상적이지않다면 무조건 로그인처리로 로직 수정 및 로그아웃 api 함수 적용
  apis/customAxios.ts
Labels: update

#137 FE: 카드컴포넌트 및 마이페이지 css 재조정
  components/Alarm/styled.ts
  components/Card/ApplyCard/styled.ts
  components/Card/ProjectCard/styled.ts
  components/Tag/TagBox/index.tsx
  components/Tag/TagBox/styled.ts
  components/pages/landing/first/styled.ts
  components/pages/mypage/Profile/Info/styled.ts
  components/pages/mypage/Profile/styled.ts
  components/pages/mypage/TabApplyBoards/styled.ts
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/recruits/RecruitList/styled.ts
  pages/mypage/[mypageId].tsx
  pages/mypage/profileEdit/index.tsx
Labels: design

#142 FE: UXUI 수정
  components/Alarm/AlarmList.tsx
  components/Alarm/index.tsx
  components/Alarm/styled.ts
  components/Card/ApplyCard/styled.ts
  components/Card/ProjectCard/index.tsx
  components/Header/LoggedInMenuBox/index.tsx
  components/pages/mypage/TabBoards/index.tsx
  hooks/mutations/useDeleteAccount.ts
  hooks/mutations/useEditProfile.ts
  hooks/queries/useGetAlarmDataAll.ts
  hooks/queries/useGetMypageData.ts
  hooks/queries/useGetPofileData.ts
  pages/mypage/profileEdit/index.tsx
Labels: update, design

#143 update: 회원가입시 포트폴리오 정보 넣을수 있게 추가 및 palaceholder 설정
  components/Modals/LoginModal/RegisterView/RegisterUserInfo.tsx
Labels: update

#146 Fix/bug fix
  apis/NotificationAPI.ts
  components/Banner/index.tsx
  components/Banner/styled.ts
  components/Card/ProjectCard/index.tsx
  components/Card/RankingCard/index.tsx
  components/Card/RecruitCard/index.tsx
  components/Carousel/BatchCarousel/index.tsx
  components/Carousel/BatchCarousel/styled.ts
  components/Carousel/MainCarousel/index.tsx
  components/Carousel/MainCarousel/styled.ts
  components/Header/GlobalNavBar/styled.ts
  components/Layout/index.tsx
  components/Nodata/index.tsx
  components/pages/detailPage/CommentBox/index.tsx
  components/pages/detailPage/CommentBox/styled.ts
  components/pages/detailPage/CommentItem/styled.ts
  components/pages/detailPage/ContentDetail/index.tsx
  components/pages/detailPage/ContentDetail/styled.ts
  components/pages/detailPage/Popup/index.tsx
  components/pages/detailPage/Popup/styled.ts
  components/pages/detailPage/PostData/index.tsx
  components/pages/detailPage/PostData/styled.ts
  components/pages/landing/styled.ts
  components/pages/mypage/Profile/Introduction/index.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  enum/index.ts
  pages/projects/[projectId].tsx
  pages/projects/index.tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/index.tsx
  public/images/projects-banner-sample.jpg
Labels: feat, fix

#153 FE: 알람 및 마이페이지 UX 개선
  README.md
  components/Alarm/AlarmList.tsx
  components/Alarm/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/avatar.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/Introduction/introduction.tsx
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/mypageEdit/Skill/index.tsx
  components/pages/mypageEdit/index.tsx
  hooks/common/useInputImage.ts
  hooks/common/withAuth.tsx
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
  utils/updateData.ts
Labels: update, fix

#154 FE: 이미지 추가 및 알람 로직 수정
  README.md
  components/Alarm/AlarmList.tsx
  public/readme-images/logo.png
Labels: fix
