Repository Side-Effect-Team/side-effect-frontend, pull requests merged in 2023-04, with the labels that each got.

#8 Feat/회원정보등록페이지
  components/Layout.tsx
  components/PageTransition.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/userinfo/image.tsx
  pages/userinfo/index.tsx
  pages/userinfo/position.tsx
  store/hooks.ts
  store/pageTransitionSlice.ts
  store/store.ts
  styles/Media.ts
Labels: feat, fix

#9 Theme.ts 파일 수정
  styles/Theme.ts
Labels: design

#14 fix:컴포넌트명 첫글자 소문자에서 대문자로 변경
  Enum/index.ts
  components/Header/index.tsx
  pages/userinfo/image.tsx
  pages/userinfo/index.tsx
  pages/userinfo/position.tsx
Labels: fix

#23 Feat/card컴포넌트
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  pages/index.tsx
  public/img/BoardDefaultBackground.png
  public/img/ProjectDefaultBackground.png
Labels: feat

#27 FE: 캐러셀 컴포넌트 구현
  components/Carousel/index.tsx
  components/Carousel/styled.ts
  components/Layout/index.tsx
  components/Layout/styled.ts
  enum/index.tsx
  pages/index.tsx
  public/.gitkeep
  public/images/sample1.svg
  public/images/sample2.svg
  public/images/sample3.svg
  styles/Theme.ts
Labels: feat, refactor

#28 FE: 드랍다운 셀렉트박스 리팩토링
  components/Layout/index.tsx
  components/SelectBox/index.tsx
  components/pages/UserInfoPage/ErrorMessage.tsx
  components/pages/UserInfoPage/PageTransition.tsx
  package-lock.json
  package.json
  pages/userinfo/image.tsx
  pages/userinfo/index.tsx
  pages/userinfo/position.tsx
  store/pageTransitionSlice.ts
  store/userInfoSlice.ts
Labels: update, refactor
