Repository Side-Effect-Team/side-effect-frontend, pull requests merged in 2023-05, with the labels that each got.

#30 Feat/마이페이지
  components/pages/Mypage/Detail/index.tsx
  components/pages/Mypage/Detail/styled.ts
  pages/mypage/index.tsx
Labels: feat

#32 FE: 유저정보등록 성공페이지 구현 및 userinfo 페이지 스타일 컴포넌트 분리
  components/SelectBox/index.tsx
  components/SelectBox/styled.ts
  components/pages/UserInfoPage/ErrorMessage.tsx
  components/pages/UserInfoPage/PageTransition.tsx
  components/pages/UserInfoPage/styled.ts
  pages/userinfo/image.tsx
  pages/userinfo/index.tsx
  pages/userinfo/position.tsx
  pages/userinfo/success.tsx
  store/pageTransitionSlice.ts
  store/userInfoSlice.ts
Labels: feat, design

#33 FE: 모집 페이지 구현
  components/Banner/index.tsx
  components/Banner/styled.ts
  components/BoardCard/styled.ts
  components/Button/styled.ts
  components/Header/index.tsx
  components/Layout/index.tsx
  components/pages/Mypage/Detail/index.tsx
  enum/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/recruits/[recruitId].ts
  pages/api/recruits/data.json
  pages/api/recruits/index.ts
  pages/mypage/index.tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/add.tsx
  pages/recruits/index.tsx
  public/images/BoardDefaultBackground.png
  public/images/ProjectDefaultBackground.png
  public/images/recruits-banner-sample.jpg
  styles/Global.ts
  styles/Theme.ts
Labels: feat, chore

#36 FE: 마이페이지 수정페이지 구현
  components/pages/Mypage/Detail/index.tsx
  components/pages/Mypage/Detail/styled.ts
  components/pages/Mypage/Info/index.tsx
  components/pages/Mypage/Info/styled.ts
  components/pages/Mypage/Introduction/index.tsx
  components/pages/Mypage/Introduction/styled.ts
  components/pages/Mypage/Skill/index.tsx
  components/pages/Mypage/Skill/styled.ts
  components/pages/Mypage/styled.ts
  components/pages/MypageEdit/Info/index.tsx
  components/pages/MypageEdit/Info/styled.ts
  components/pages/MypageEdit/Introduction/index.tsx
  components/pages/MypageEdit/Introduction/styled.ts
  components/pages/MypageEdit/Skill/index.tsx
  components/pages/MypageEdit/Skill/styled.ts
  pages/mypage/edit/index.tsx
  pages/mypage/index.tsx
Labels: feat

#37 FE: 프로젝트 자랑게시판 구현
  components/SelectBox/index.tsx
  components/SelectBox/styled.ts
  package-lock.json
  package.json
  pages/projects/index.tsx
Labels: feat

#39 FE: 커스텀 훅 추가, path alias 설정 및 모집 게시글 등록 기능 테스트
  components/BoardCard/styled.ts
  enum/index.ts
  hooks/useInputImage.ts
  hooks/useLocalStorage.ts
  pages/_app.tsx
  pages/index.tsx
  pages/post/project.tsx
  pages/post/recruit.tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/add.tsx
  pages/recruits/index.tsx
  public/images/default-input-image.png
  tsconfig.json
Labels: feat, refactor, chore

#40 FE: card컴포넌트 수정
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  pages/api/recruits/data.json
  pages/projects/[projectId].tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
Labels: feat, fix, design

#41 FE: 마이페이지 수정페이지 변경사항 및 카드컴포넌트 레이아웃 변경
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  components/pages/mypage/Info/index.tsx
  components/pages/mypage/Info/styled.ts
  components/pages/mypage/Introduction/index.tsx
  components/pages/mypage/Introduction/styled.ts
  components/pages/mypage/Skill/index.tsx
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/Introduction/styled.ts
  components/pages/mypageEdit/Skill/index.tsx
  pages/mypage/edit/index.tsx
  pages/mypage/index.tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
Labels: design, chore

#43 FE: 팀 관리모달 레이아웃 구현
  components/Modals/GlobalModal.tsx
  components/Modals/ManageCard.tsx
  components/Modals/ManageTeamModal.tsx
  hooks/useFilterTab.ts
  hooks/useOutsideClick.ts
  pages/_app.tsx
  pages/projects/index.tsx
  public/images/profilePic.png
  store/modalSlice.ts
  store/store.ts
  styles/Theme.ts
  styles/mediatest.ts
Labels: feat

#44 FE: 프로젝트관리모달 필터탭 추상화 및 css 수정
  components/Modals/GlobalModal.tsx
  components/Modals/ManageTeamModal.tsx
  components/Modals/ManageTeamModal/FilterTab.tsx
  components/Modals/ManageTeamModal/ManageCard.tsx
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Modals/ManageTeamModal/PositionFilterTab.tsx
  components/SelectBox/styled.ts
  components/pages/userInfoPage/PageTransition.tsx
  components/pages/userInfoPage/styled.ts
  hooks/useFilterTab.ts
  package-lock.json
  package.json
  pages/projects/index.tsx
  pages/userinfo/index.tsx
  pages/userinfo/position.tsx
  pages/userinfo/success.tsx
  store/modalSlice.ts
Labels: design, refactor

#46 FE: 검색 기능 인풋창 구현
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  components/Search/filter.tsx
  components/Search/index.tsx
  components/Search/styled.ts
  components/pages/mypage/Info/styled.ts
  components/pages/mypage/Introduction/index.tsx
  components/pages/mypageEdit/Info/styled.ts
  pages/mypage/edit/index.tsx
  pages/mypage/index.tsx
  pages/projects/index.tsx
Labels: feat, update

#49 FE: 토스트컴포넌트 #47
  .gitignore
  components/Header/index.tsx
  components/Layout/index.tsx
  components/Modals/GlobalModal.tsx
  components/Modals/LoginModal/LoginModal.tsx
  components/Modals/ManageTeamModal/ManageCard.tsx
  components/Toast/index.tsx
  components/Toast/styled.ts
  hooks/useToast.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/projects/index.tsx
  store/modalSlice.ts
  store/store.ts
  store/toastSlice.ts
Labels: feat, design

#55 FE : SelectBox 기능수정 및 디자인수정 #53
  components/SelectBox/index.tsx
  components/SelectBox/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  pages/projects/index.tsx
  pages/userinfo/position.tsx
Labels: update, design

#56 FE: 게시글 작성 기능 구현
  components/BoardCard/styled.ts
  components/pages/post/PositionBox/index.tsx
  components/pages/post/PositionBox/styled.ts
  components/pages/post/ProjectUrlBox/index.tsx
  components/pages/post/TagBox/index.tsx
  components/pages/post/TagBox/styled.ts
  components/pages/post/common/PageLayout.styled.ts
  components/pages/post/common/PostForm.styled.ts
  components/pages/post/common/Title.styled.ts
  enum/index.ts
  hooks/useForm.ts
  hooks/useTag.ts
  pages/post/project.tsx
  pages/post/recruit.tsx
  styles/Theme.ts
  tsconfig.json
Labels: feat

#57 FE :ScrollToTop 컴포넌트 구현 #51
  components/Layout/index.tsx
  components/ScrollToTop/index.tsx
  components/ScrollToTop/styled.ts
Labels: feat

#61 FE: 토스트컴포넌트 예외발생 타입 추가 및 디자인 수정
  components/Modals/ManageTeamModal/ManageCard.tsx
  components/Toast/index.tsx
  components/Toast/styled.ts
  hooks/useToast.ts
  store/toastSlice.ts
Labels: update, design

#62 FE: 마이페이지탭 구현
  components/BoardCard/index.tsx
  components/Button/styled.ts
  components/pages/mypage/Info/index.tsx
  components/pages/mypage/Introduction/index.tsx
  components/pages/mypage/Profile/Info/index.tsx
  components/pages/mypage/Profile/Info/styled.ts
  components/pages/mypage/Profile/Introduction/index.tsx
  components/pages/mypage/Profile/Introduction/styled.ts
  components/pages/mypage/Profile/Skill/index.tsx
  components/pages/mypage/Profile/Skill/styled.ts
  components/pages/mypage/Profile/index.tsx
  components/pages/mypage/Profile/styled.ts
  components/pages/mypage/TabBoards/index.tsx
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/Skill/index.tsx
  components/pages/mypageEdit/styled.ts
  pages/mypage/edit/index.tsx
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
Labels: feat

#64 FE: 게시글 작성 기능 구현
  components/Layout/index.tsx
  pages/_document.tsx
  pages/post/project.tsx
  pages/post/recruit.tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/index.tsx
  tsconfig.json
  types/recruit.ts
  utils/converter.ts
  utils/getTodayDate.ts
Labels: feat

#65 FE: 프로젝트관리모달
  components/Modals/ManageTeamModal/FilterTab.tsx
  components/Modals/ManageTeamModal/ManageCard.tsx
  components/Modals/ManageTeamModal/ManageList.tsx
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Modals/ManageTeamModal/PositionFilterTab.tsx
  components/Modals/ManageTeamModal/WaitingImage.tsx
  hooks/useFilterTab.ts
  pages/projects/index.tsx
  public/images/Waiting.png
Labels: feat

#66 FE: 마이페이지탭 수정
  components/BoardCard/index.tsx
  components/Search/filter.tsx
  components/pages/mypage/Profile/Info/index.tsx
  components/pages/mypage/Profile/index.tsx
  components/pages/mypage/TabBoards/index.tsx
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  components/pages/mypageEdit/Info/index.tsx
  components/pages/mypageEdit/Introduction/index.tsx
  components/pages/mypageEdit/styled.ts
  pages/mypage/[mypageId].tsx
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
Labels: feat, design

#68 FE: 알림창 구현
  components/Alarm/AlarmList.tsx
  components/Alarm/index.tsx
  components/Alarm/styled.ts
  components/Header/index.tsx
  components/Header/styled.ts
  components/MobileMenuBox/index.tsx
  components/MobileMenuBox/styled.ts
  pages/index.tsx
  pages/mypage/profileEdit/index.tsx
Labels: feat

#73 FE: 알림창 로직 수정
  components/Alarm/AlarmList.tsx
  components/Alarm/AlarmQurey.tsx
  components/Alarm/index.tsx
  components/Alarm/styled.ts
  components/BoardCard/index.tsx
  components/pages/mypage/TabBoards/index.tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
Labels: update

#74 FE: 좋아요 임시 리패치
  components/BoardCard/index.tsx
  components/pages/mypage/TabBoards/index.tsx
Labels: update

#76 Feat/carousel temp
  components/BoardCard/styled.ts
  components/Carousel/BatchCarousel/index.tsx
  components/Carousel/BatchCarousel/styled.ts
  components/Carousel/MainCarousel/index.tsx
  components/Carousel/MainCarousel/styled.ts
  pages/index.tsx
  pages/projects/index.tsx
  pages/recruits/index.tsx
  styles/Theme.ts
Labels: feat

#77 FE: 마이페이지 및 알림창 수정
  components/Alarm/AlarmList.tsx
  components/Alarm/AlarmQurey.tsx
  components/Alarm/index.tsx
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  components/Header/index.tsx
  components/MobileMenuBox/index.tsx
  components/pages/mypage/Account/index.tsx
  components/pages/mypage/Account/style.ts
  components/pages/mypageEdit/Introduction/index.tsx
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
Labels: feat, fix

#78 FE: 소셜로그인 구현
  components/Layout/index.tsx
  components/Modals/LoginModal/Login.tsx
  components/Modals/LoginModal/LoginModal.tsx
  components/Modals/LoginModal/LoginTitle.tsx
  components/Modals/LoginModal/OAuthLoginButton/GoogleLoginButton.tsx
  components/Modals/LoginModal/OAuthLoginButton/KakaoLoginButton.tsx
  components/Modals/LoginModal/OAuthLoginButton/NaverLoginButton.tsx
  components/Modals/LoginModal/OAuthLoginButton/styled.ts
  components/Modals/LoginModal/RegisterView/ErrorMessage.tsx
  components/Modals/LoginModal/RegisterView/RegisterNickname.tsx
  components/Modals/LoginModal/RegisterView/RegisterSuccess.tsx
  components/Modals/LoginModal/RegisterView/RegisterUserInfo.tsx
  components/Modals/LoginModal/RegisterView/styled.ts
  components/SelectBox/index.tsx
  components/SelectBox/styled.ts
  components/pages/userInfoPage/PageTransition.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/userinfo/success.tsx
  public/images/Github.png
  public/images/Google.png
  public/images/Kakao.png
  store/authSlice.ts
  store/loginViewTransitionSlice.ts
  store/pageTransitionSlice.ts
  store/store.ts
  store/userInfoStoreSlice.ts
Labels: feat

#81 FE: 프로젝트 자랑게시판 페이지 리팩토링
  apis/ProjectAPI.ts
  components/Alarm/AlarmList.tsx
  components/Alarm/index.tsx
  components/BoardCard/index.tsx
  components/Header/index.tsx
  components/Loading/index.tsx
  components/Loading/styled.ts
  components/Modals/LoginModal/OAuthLoginButton/GoogleLoginButton.tsx
  components/Modals/LoginModal/OAuthLoginButton/KakaoLoginButton.tsx
  components/Modals/LoginModal/RegisterView/RegisterUserInfo.tsx
  components/Modals/ManageTeamModal/ManageCard.tsx
  components/Modals/ManageTeamModal/ManageTeamModal.tsx
  components/Nodata/index.tsx
  components/Nodata/styeld.ts
  components/SelectBox/index.tsx
  components/Toast/index.tsx
  components/pages/mypage/Account/index.tsx
  components/pages/project/ProjectLIst/index.tsx
  components/pages/project/ProjectLIst/styled.ts
  hooks/common/useFilterTab.ts
  hooks/common/useForm.ts
  hooks/common/useInputImage.ts
  hooks/common/useLocalStorage.ts
  hooks/common/useOutsideClick.ts
  hooks/common/useTag.ts
  hooks/common/useToast.ts
  hooks/queries/useGetProjectData.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/mypage/profileEdit/index.tsx
  pages/post/project.tsx
  pages/post/recruit.tsx
  pages/projects/edit/[projectId].tsx
  pages/projects/index.tsx
  pages/recruits/edit/[recruitId].tsx
  public/images/Nodata.png
Labels: feat, refactor

#85 FE: 카드컴포넌트, 마이페이지 탭 디자인 수정
  apis/LikeAndCommentAPI.ts
  apis/NotificationAPI.ts
  apis/ProjectAPI.ts
  apis/RecruitBoardAPI.ts
  apis/UserAPI.ts
  components/Alarm/AlarmList.tsx
  components/Alarm/index.tsx
  components/BoardCard/index.tsx
  components/BoardCard/styled.ts
  components/Header/index.tsx
  components/MobileMenuBox/index.tsx
  components/pages/mypage/Profile/Info/index.tsx
  components/pages/mypage/Profile/Skill/index.tsx
  components/pages/mypage/Profile/index.tsx
  components/pages/mypage/TabBoards/index.tsx
  components/pages/mypage/TabBoards/styled.ts
  components/pages/mypage/styled.ts
  hooks/mutations/useAddLikeProject.tsx
  hooks/mutations/useAddLikeRecuit.tsx
  hooks/mutations/useDeleteAlarm.tsx
  hooks/mutations/useEditProfile.tsx
  hooks/mutations/useReadAlarm.tsx
  hooks/queries/useGetAlarmList.tsx
  hooks/queries/useGetMypageData.tsx
  hooks/queries/useGetPofileData.tsx
  pages/mypage/[mypageId].tsx
  pages/mypage/index.tsx
  pages/mypage/profileEdit/index.tsx
Labels: design, refactor

#90 FE: 스켈레톤 컴포넌트 구현
  apis/ProjectAPI.ts
  components/Skeleton/BoardCardSkeleton/index.tsx
  components/Skeleton/BoardCardSkeleton/styled.ts
  components/pages/project/ProjectLIst/index.tsx
  components/pages/project/ProjectLIst/styled.ts
  hooks/queries/useGetProjectData.tsx
  pages/projects/index.tsx
Labels: feat

#91 FE: 알림창 무한스크롤 적용
  apis/NotificationAPI.ts
  components/Alarm/AlarmList.tsx
  components/Alarm/index.tsx
  components/Alarm/styled.ts
  components/Skeleton/AlarmSkeleton/index.tsx
  components/Skeleton/AlarmSkeleton/styled.ts
  hooks/mutations/useAddLikeProject.ts
  hooks/mutations/useAddLikeRecuit.ts
  hooks/mutations/useDeleteAlarm.ts
  hooks/mutations/useEditProfile.ts
  hooks/mutations/useReadAlarm.ts
  hooks/queries/useGetAlarmData.tsx
  hooks/queries/useGetAlarmDataAll.ts
  hooks/queries/useGetAlarmList.tsx
  hooks/queries/useGetAlarmNum.ts
  hooks/queries/useGetMypageData.ts
  hooks/queries/useGetPofileData.ts
Labels: feat, update

#92 FE: 프로젝트 자랑 게시글 댓글 기능 추가
  components/pages/detailPage/CommentBox/index.tsx
  components/pages/detailPage/CommentBox/styled.ts
  components/pages/detailPage/CommentItem/index.tsx
  components/pages/detailPage/CommentItem/styled.ts
  components/pages/detailPage/ContentDetail/index.tsx
  pages/projects/[projectId].tsx
  pages/projects/edit/[projectId].tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/edit/[recruitId].tsx
  pages/recruits/index.tsx
  types/projects.ts
  types/recruit.ts
  utils/converter.ts
Labels: feat

#94 FE: 헤더 및 모바일 헤더의 로그인/로그아웃 UI 변경
  components/Header/index.tsx
  components/Layout/index.tsx
  components/MobileMenuBox/index.tsx
  enum/index.ts
  hooks/common/useLocalStorage.ts
Labels: feat

#100 FE: refresh token
  apis/UserAPI.ts
  apis/customAxios.ts
  components/Layout/index.tsx
  components/Modals/LoginModal/OAuthLoginButton/GoogleLoginButton.tsx
  hooks/common/useLogin.ts
  hooks/queries/useGetProjectData.tsx
  pages/projects/index.tsx
  store/authSlice.ts
  utils/auth.ts
Labels: fix

#102 FE: ScrollToTop버튼 z-index 수정 #101
  components/ScrollToTop/styled.ts
Labels: design

#103 FE: customAxios 액세스토큰 에러핸들링 코드 변경
  apis/customAxios.ts
Labels: update

#99 FE: 로그인 및 token 획득 방식 변경으로 인한 리팩토링
  components/Banner/index.tsx
  components/Carousel/BatchCarousel/index.tsx
  components/Header/index.tsx
  components/Layout/index.tsx
  components/MobileMenuBox/index.tsx
  components/pages/detailPage/CommentBox/index.tsx
  components/pages/detailPage/CommentItem/index.tsx
  components/pages/detailPage/PositionDetail/index.tsx
  components/pages/detailPage/PostData/index.tsx
  hooks/common/useInputImage.ts
  next.config.js
  pages/_app.tsx
  pages/post/project.tsx
  pages/post/recruit.tsx
  pages/projects/[projectId].tsx
  pages/projects/edit/[projectId].tsx
  pages/recruits/[recruitId].tsx
  pages/recruits/edit/[recruitId].tsx
  pages/recruits/index.tsx
  tsconfig.json
  types/projects.ts
  types/recruit.ts
Labels: feat, fix, refactor
